name: griddx
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - tqdm
  - pyyaml
  - joblib
  - tensorboard
  - openpyxl
  - pyarrow
  - plotly
  - pip:
      - --index-url https://download.pytorch.org/whl/cu128
      - torch
      - torchvision
      - torchaudio
